import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { PageFooter } from '../components/page/page-footer';
import { PageHeader } from '../components/page/page-header';

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <main>
               <PageHeader />
               <div className="mt-[57px] overflow-y-auto h-[calc(100vh-57px)]">
                  {children}
                  <PageFooter />
               </div>
            </main>
         </body>
      </html>
   );
}
